language: node_js
sudo: false
node_js:
- '7'
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - DEBUG='* -superagent -express:* -mocha:* -babel -nock* -eslint*'
  - secure: "6z9W+V+eSo1+x+dNKpxxkak9t7jjCAvAsSP7eaATEdnUJ+N0bTaF57be+KKEOkyuR8WjJFYvWtf85m4zq9qIWyfufUlhAaOtxiN52Jgkua0pTn1rBQYFdEqzgJx+pdqjmRYkjoSEy3H3UuaJSEpY5zEcEI9328lrq52FSM6zV1E0jerb97zHxYcVvBtKE89SEl0ezpgAePC6F09Pqy+1KHIHJLmCAT5N/LhE6KOZJTUImbfjwFLy05Jb3OOYAJYYaTWx0gsvbwpIVysBmGHdLNiajUxho4aulw+SddTBhf2y0y1j34+YK2AOdYW+RCNBC3SCxEBn5RG5FylWZoYaZLl4iK5y3OpKluc/kpNwr8mzBeCGoNrWSw0BQy9JmFzWS14Qst2qN5MIKl2TKYonesq8suLlvoDpQULVV6bL2Q+O5kuuC6mvlxkei4f4oOOc49rnrgi5l9gbHNp3/HfrpjRXTvVJlCWRkOmB8zcX+cNz4y2MxOpgVdYgMc44eEkmxa6OkmCN4jCWI+Mz56JfRzmP1S9bpSvuRBf8oA+6BS7iIVOExXtCUCEs/YFo/zBafb3C4WPo07rLs6iEzVYMAa3RaoZvSL/PMtXV+Wbdr26qcAlPme2PdpZYcI/ZukJm5asuBN2w2kRa91iussMUqPEJp5aa0fVH9HCZDaGcvFg="
  - secure: "gma0lZHQclKkMZDTDF2XWbRFslmwle3eJDt8URx1UphowQqSnfglnqC19+zv/ZAskuJVLdtEiuTONqns59wuiYbkKRehqqzESMRhGd9kjEuHBKd5bWHVZDCt/vvWTV14U05DFJalx2/BsoysZdiDTfRS8kk5ORrCPqbgM6YY5IzYPfWu06mBsD9CN9jfqgUzCVd0+H03yfrs9S0esI5fGjV9FmqmCqqu2fdyAlTQNsv09LNXalKPp71dzV1G+ex62Vg31uR2s9RtH/AQ3YXcQKoyWLDRifwYZ9W37E8+bwsAKGvNe7AHjcXeYcXw8sfWu/hgRA96BjXXhZV+bQz/eYE0oWXB6+MORf2Q3imcTi2ixLtvI/PyO3/1CDp5OSXrqqxguN+p0QvNtTQKICsQzs8FyAJIcL/nqEJ7WFT4LszqYLnVNgPfd72tCeeMppOxERNRYFKJtGQruj98nMUdGML6gtYo/wAqbDn9qtdg+uG80dYvIpZ+YNiYBwjfo7JOzENHTHroVKDtHSUp5VC9JrnPsJTS1H/tmKv1wF4w1Tt0OiWPocCgIXHo8GuAECA8/Arf1XPA3QjRwQhVvRnpgaimqYAvG6KFK0yaKiXM5/2RYt+vI2TW03ytYvvsRHHok78HeXUsuUFzG/XciFfj/QisQ8M1yMNtA8mQJBEB3D0="
notifications:
  irc:
    channels:
    - secure: qF+kt+bGzSxK8jiD5hACkx1Rnbh3Dcy6g9EO4Qqsjem2w2dBHbPSOeePvum50fO6ShcpmqCWCFYqclgDfMJq03mUMzHSidlNjCvNOPnrn3SJ0RUOcNRrM00lf5UjDLoCRtNFypjGJoyz2kCbbVxHpBIzIlq9MCiIQ+X9JIrptz6GhLiRqEjnk14FeJgr9rWFlruzKt5h0EzP077KZUY7/pwMWahdAtTEKGaoef/I6F8rWb6s/xJX1Xw5J3Jxq1gDI9usC3JbMEVV+gvqHsE5RVBTJRK0a8u9jMFaCeBX21qvfHg4AWjEsTg7plnWZcTHEmNUjO9SHorcTpGIUk5bOHHs8Xv42vkfyHHPd8hg2NU/F/2GVEyXaVHlusOfcHAlDBpZ81SeIfcaOL/ueQmRnd2+nrDQ+SOjKbSn8QGjDzkZ4OL/lT3o29ej4ZkDsCgRRpN2rW0Opoe26Khs80tx3mK2bcq9rAGR9+/pnC9SZU/dHYpKioNLCoAMmnxfPNY4/YdAmLhUazCafhPa9qa2zxFu9fWh7oLtfTfmLkhx8AFysgk+7t/0SYWwEccJZ0dUtdcMUYRXNp5QmqA3srKZyQSDIhu/ncglqCBTW5pRULc2Ycgc3SjTFMmHjCK3cpW819DHrfkhy6mz+yCf8lV8UK8VHcCXDK8l5vGb0ZRrLDs=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: bbR2yr4KfG5Uce4qZfT3BZNBROKuM1VqRSa6oekC1E+N5lgMoSersIo121GZNhIwu7TnEt15mo4fTvmrNDnOqrsd9n1BaalwFhDMF4MTrBXdshBvK9xk9oECbmSmv3kV4Xbq/63Ml+MljFOJ35WW7poKcVLAVKIE7V/eup3EBkyoJINZXNBNwFJvQsnL2MZ5jy14IfXmGbyBNWQtZ1UODa54/NswzPQgErLuIoa0j/P2Yeiv2zVolwYySqtrEurUr+9v4mIPg4HE+NnCjUKQa5PSN9m1ObUnEPa0SR99cbs6NwouI9lI4WFZyLU9lxSp8Yz9S5T2lHukZzltT24fHFBKLQsiedqJzqm9I7avHcw41YEc4dKinK2Bxqlnaf1rcmhpWRKX4Fmwein4st6y6XFigRGTuiW5nOaCbNibGVaqE5GJiEfseNa1L84VIxDsVnHXforjj4Ep7dr5/TjRMO9tnOzYpGyFs9hGh1yY7iDU6WaBTDinlvniK8N4zniqxlgMYWwBu99ePHxfCEU7RHFo28Z04FzTNgr/wAFI6UWM2Ey4yyBOSBh5yZd4G4UnWZldNaa04njK6Tz7gMz3D9sEJTXPHuVshErmAlNAJnRbBgbJSo7g6A1Y+gQUA3AbR1Xyk1TTNmctukmyH38n3FtuAtkQCgcLfonaMe9/UEw=
  on:
    tags: true
    repo: taskcluster/azure-entities
