language: node_js
sudo: false
node_js:
- '7'
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - DEBUG='* -superagent -express:* -mocha:* -babel -nock* -eslint*'
  - secure: kbjHjTjelurgc2HJNiy5WbTMS4tTzKRGLF5sKVo2YQ27tK57fSbqm4dwgghkNX1DgVOg9P9m+IzGnRY+3f2Suwz8+rCZbi28pvfS0wLblyWgA526WBrY/W2ceh47IWmdIl3Y9xmzy9zia0hAux71JWY2kuhkxXxdSSmSj+p7bt9Mvptr/BxCdZvpmkt6vNHWw+7/dMqySMpk2hDIkb420haKOSuoWVcoXkBmF/Y2x7jg7EZgT2a6UutBl5c1F+G7RzibICBpdGn3FFKv05Kxwm2r9e4emOP0eYg65UQepvzG+TVSTe3IAY7SFEs5ax/3hYPObdXMTzlFk9Iak2vqNB7lDKgwAj83uWvn9nNERm+tKh652r6r++Xxf/CbpFmYeD0HQICC0/EkFTKgefhtb5GYzP9MBRiSUoj/oIsNAyMp8xbvhkBnYJj7ppXp0kFEnbiNjduseJ88yqtlNSFvaV0WtORUoB4Cqxj3wbaShFinXGGXjiXiCA7z8QNuJeqZ5oI1O3v/BNDDr5b/DOTsDwU9JBhMOCbBRp34uK+IugRKj1eXCMNz8I1IOFu8/iSeeC15Z1/77Yeb5a3MbdRqDf4Q8PY59L1EaRj0/dl6Mvl7EViSmzqfOUx80Y3Zx6oy2ALunVJ8kPIaFV+glo3WKJ3Hwcaj3ZN5IsJIrkfmUsY=
  - secure: 3s9x0jXvHqSDyCpvvAOeW/mLMc5ym/ydvR6CKSQaKiejr5JmfJ2F8PBIp55Qwlxx2mtZw4G/WKSLc0opdG5s/+dztX/61db61JEcWFlxcm+zmsFwlHaQT2JlQGP0mOs8Nb96vPNV2uNNLL/wzseHK0eJRWEYyJ/fxMsQr/PJkNH0uXxP8E7WFEB6YmWNfskQdkbxHQFQxvHaUPWZADCmvRICR+HQCl+z5ybyyglvqbRtqma4YN5pTj5upLzW8AFED2+qhkGpEIofSEyLRRtEqqnc6iSlsWem1CywQ0IpHrkyyvOzqofX0DJ+jXY7IDswt818f9Zy+YWTw5KxqikE/aaL7lcMy4s/WBykZrfmK4MI9W2/qA3rRg4SKKTQ4nHcVhgYje5a6CgwesSwHjXcUFu35GMLv1PXwVdHiLlSifaZpiq6WF/T64rMVt5UTCxO4ObEv3PaaYf45zoEszg8mVjYy4mMvk/ldWw+tRUd9R4DFLE+kOfiCMuzcj9w2wVIExZecCSBSdHEi51tiT/CkJ328csbw9KP7VGEaWl9xX0K6sCfSHYvPl+qkKZcpyBhghRk7HEQkQ5uoKuCch+Bot5lGI4Llu9WOEF78vidrVrB+HCbRnMcYPfqteXZILi7WFZ3P+8Iawzxk7wcA0554x1losNlCJjvzkCdwTVDc+8=
notifications:
  irc:
    channels:
    - secure: qF+kt+bGzSxK8jiD5hACkx1Rnbh3Dcy6g9EO4Qqsjem2w2dBHbPSOeePvum50fO6ShcpmqCWCFYqclgDfMJq03mUMzHSidlNjCvNOPnrn3SJ0RUOcNRrM00lf5UjDLoCRtNFypjGJoyz2kCbbVxHpBIzIlq9MCiIQ+X9JIrptz6GhLiRqEjnk14FeJgr9rWFlruzKt5h0EzP077KZUY7/pwMWahdAtTEKGaoef/I6F8rWb6s/xJX1Xw5J3Jxq1gDI9usC3JbMEVV+gvqHsE5RVBTJRK0a8u9jMFaCeBX21qvfHg4AWjEsTg7plnWZcTHEmNUjO9SHorcTpGIUk5bOHHs8Xv42vkfyHHPd8hg2NU/F/2GVEyXaVHlusOfcHAlDBpZ81SeIfcaOL/ueQmRnd2+nrDQ+SOjKbSn8QGjDzkZ4OL/lT3o29ej4ZkDsCgRRpN2rW0Opoe26Khs80tx3mK2bcq9rAGR9+/pnC9SZU/dHYpKioNLCoAMmnxfPNY4/YdAmLhUazCafhPa9qa2zxFu9fWh7oLtfTfmLkhx8AFysgk+7t/0SYWwEccJZ0dUtdcMUYRXNp5QmqA3srKZyQSDIhu/ncglqCBTW5pRULc2Ycgc3SjTFMmHjCK3cpW819DHrfkhy6mz+yCf8lV8UK8VHcCXDK8l5vGb0ZRrLDs=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: bbR2yr4KfG5Uce4qZfT3BZNBROKuM1VqRSa6oekC1E+N5lgMoSersIo121GZNhIwu7TnEt15mo4fTvmrNDnOqrsd9n1BaalwFhDMF4MTrBXdshBvK9xk9oECbmSmv3kV4Xbq/63Ml+MljFOJ35WW7poKcVLAVKIE7V/eup3EBkyoJINZXNBNwFJvQsnL2MZ5jy14IfXmGbyBNWQtZ1UODa54/NswzPQgErLuIoa0j/P2Yeiv2zVolwYySqtrEurUr+9v4mIPg4HE+NnCjUKQa5PSN9m1ObUnEPa0SR99cbs6NwouI9lI4WFZyLU9lxSp8Yz9S5T2lHukZzltT24fHFBKLQsiedqJzqm9I7avHcw41YEc4dKinK2Bxqlnaf1rcmhpWRKX4Fmwein4st6y6XFigRGTuiW5nOaCbNibGVaqE5GJiEfseNa1L84VIxDsVnHXforjj4Ep7dr5/TjRMO9tnOzYpGyFs9hGh1yY7iDU6WaBTDinlvniK8N4zniqxlgMYWwBu99ePHxfCEU7RHFo28Z04FzTNgr/wAFI6UWM2Ey4yyBOSBh5yZd4G4UnWZldNaa04njK6Tz7gMz3D9sEJTXPHuVshErmAlNAJnRbBgbJSo7g6A1Y+gQUA3AbR1Xyk1TTNmctukmyH38n3FtuAtkQCgcLfonaMe9/UEw=
  on:
    tags: true
    repo: taskcluster/azure-entities
