language: node_js
sudo: false
node_js:
- '8'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
  - DEBUG='* -superagent -express:* -mocha:* -babel -nock* -eslint*'
  - secure: k6qS//kpmEAmvkjmDSMMu8ZlBr697VHVxa7nKFPNjI9jBk1sm3SYtG4599Y/4VS4YopORQV9qHmkBu7JsvpBR6Oo39gdPhbBRvIvMAVycP67OXw6KrdRBtBp6ILEEzhxjy/XSLPkJZx9Ckg6u2n09HojDKA+gnmBayY4FQfjoPm+2cPtIRgOsHty7KRhKUnXG2nNMXm2bqCwm+YpHi+Ss+998HFJW11zyja80FO6mB2QGp/YSpbPMizIbxfOmvBfPtXMpRJlg1vgX/ayy5s4zYIgOUTkJXWBMwH5sR98wsnZIgdiguM2y4I96b5y+MDR56h0UTZsjnTSH1JSrz0TVOtJlvCCTv0WIgfa/TXEQ/ydKbBToX+WdvEPh007LecOgJ2F/Y2XoVUBytKkrn47B+S/5Zk6B8aPbQ7voUdav2N0qvHju20Y8wsHMnMHaJ/7CrVMhbHiWXUOITlZVT4BNG5eLwWT2RfTq27bUtOyCmD45A2t09ywYbcnv1TGiIdq4XboSb4KqAYLdnY1AKgHWd1X7hcla6M5av40eYF0KIeFNJcc6Yef9Y8GR5dF+WuC3GRR/o6kw/mrm+Bxwg3kutRKvf+beGrmNaS6Ev8HAej6dDMsGc9bdaXs7D4dnkfRsydp3Ceo1bClzOwMeGlJvDxSqOu4+mPDHS0sn/7IRBk=
  - secure: gma0lZHQclKkMZDTDF2XWbRFslmwle3eJDt8URx1UphowQqSnfglnqC19+zv/ZAskuJVLdtEiuTONqns59wuiYbkKRehqqzESMRhGd9kjEuHBKd5bWHVZDCt/vvWTV14U05DFJalx2/BsoysZdiDTfRS8kk5ORrCPqbgM6YY5IzYPfWu06mBsD9CN9jfqgUzCVd0+H03yfrs9S0esI5fGjV9FmqmCqqu2fdyAlTQNsv09LNXalKPp71dzV1G+ex62Vg31uR2s9RtH/AQ3YXcQKoyWLDRifwYZ9W37E8+bwsAKGvNe7AHjcXeYcXw8sfWu/hgRA96BjXXhZV+bQz/eYE0oWXB6+MORf2Q3imcTi2ixLtvI/PyO3/1CDp5OSXrqqxguN+p0QvNtTQKICsQzs8FyAJIcL/nqEJ7WFT4LszqYLnVNgPfd72tCeeMppOxERNRYFKJtGQruj98nMUdGML6gtYo/wAqbDn9qtdg+uG80dYvIpZ+YNiYBwjfo7JOzENHTHroVKDtHSUp5VC9JrnPsJTS1H/tmKv1wF4w1Tt0OiWPocCgIXHo8GuAECA8/Arf1XPA3QjRwQhVvRnpgaimqYAvG6KFK0yaKiXM5/2RYt+vI2TW03ytYvvsRHHok78HeXUsuUFzG/XciFfj/QisQ8M1yMNtA8mQJBEB3D0=
notifications:
  irc:
    channels:
    - secure: qF+kt+bGzSxK8jiD5hACkx1Rnbh3Dcy6g9EO4Qqsjem2w2dBHbPSOeePvum50fO6ShcpmqCWCFYqclgDfMJq03mUMzHSidlNjCvNOPnrn3SJ0RUOcNRrM00lf5UjDLoCRtNFypjGJoyz2kCbbVxHpBIzIlq9MCiIQ+X9JIrptz6GhLiRqEjnk14FeJgr9rWFlruzKt5h0EzP077KZUY7/pwMWahdAtTEKGaoef/I6F8rWb6s/xJX1Xw5J3Jxq1gDI9usC3JbMEVV+gvqHsE5RVBTJRK0a8u9jMFaCeBX21qvfHg4AWjEsTg7plnWZcTHEmNUjO9SHorcTpGIUk5bOHHs8Xv42vkfyHHPd8hg2NU/F/2GVEyXaVHlusOfcHAlDBpZ81SeIfcaOL/ueQmRnd2+nrDQ+SOjKbSn8QGjDzkZ4OL/lT3o29ej4ZkDsCgRRpN2rW0Opoe26Khs80tx3mK2bcq9rAGR9+/pnC9SZU/dHYpKioNLCoAMmnxfPNY4/YdAmLhUazCafhPa9qa2zxFu9fWh7oLtfTfmLkhx8AFysgk+7t/0SYWwEccJZ0dUtdcMUYRXNp5QmqA3srKZyQSDIhu/ncglqCBTW5pRULc2Ycgc3SjTFMmHjCK3cpW819DHrfkhy6mz+yCf8lV8UK8VHcCXDK8l5vGb0ZRrLDs=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: wqgn1cEKwXY+qXg0vGAy27GovtWiH//jGWMxxdrDW+vyUblygKvDCBDH6GOyDoVbK8+gUuIzDgkiwz2Rv2LZBPrWkrl+ULNxWwhIigG0cbTjzgDunaidibF7nRBU9VP/oJUtostjqH/P6hInc7jBoyzqhCbGNT4vfvW18UC93tzNTcKHjdq8pDFC9rexOXkzIGH8XJKBy3gt53mSRQhV78hjV87PsJpNjtJjWKIOdahGb9Qogani1UMmFqbJVC8LHcwCj4gVluJ8dBtr1l8axlBdZaVLP8ISIm5bYYARQ7s8ggq7pp8626TSqXaDh+fqAeKKvrWQSyah1QKBzJM7lYH5nPbOp+kJCFT4khR91OoCsQMODJW5SLszIMUQ5N7qRtPafGB6rNR+Rk/aELT7U1JhGVkleh8KPAYCV4M+G1SdSgH+r+u+YOv+0NuBiEaa63er3xOTHgnTKyEiL/grnCP1x5nhOV9Df0v9ZdT2HVQGkj166vuRirxFyQBbFyDNhdVtXHrqSkYI029E+d2DB1HFYpBn7sRNv5H6M1uGRcwmBDCqiUNfqA5RwAu7iIXC8omIFpoNCT+qfvqYoTXlUwqxi/zxjp1yeqh8E+4R350VDv5s4p0cSSNC1W+7k7iPLPvlsvCLuLV8+ogg1MWxPZ/fCqu5OF/NEAgHN1blGKY=
  on:
    tags: true
    repo: taskcluster/azure-entities
